server:
  port: 8090

spring:
  application:
    name: Redis-Tutorial
  data:
    redis:
      host: localhost
      port: 6379
      password: YOUR_PASSWORD
  datasource:
    url: jdbc:postgresql://YOUR_DATABASE_IP_ADDRESS:5432/YOUR_DB
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect